import { useEffect, useMemo, useState } from 'react'
import { BarChart3, BookOpenCheck, CheckCircle2, CreditCard, Search, Users, UserX, UserCheck, RefreshCw, ChevronLeft, ChevronRight } from 'lucide-react'
import { api, BACKEND_URL } from '../lib/api'
import { useToast } from '../context/ToastContext'
import { PageSkeleton } from '../components/Skeleton'
import Breadcrumbs from '../components/Breadcrumbs'

export default function AdminPage(){
 const {toast}=useToast(); const [stats,setStats]=useState(null); const [payments,setPayments]=useState([]); const [users,setUsers]=useState([]); const [error,setError]=useState(''); const [q,setQ]=useState(''); const [paymentStatus,setPaymentStatus]=useState(''); const [role,setRole]=useState(''); const [loading,setLoading]=useState(true); const [paymentPage,setPaymentPage]=useState(1); const [userPage,setUserPage]=useState(1); const [paymentCount,setPaymentCount]=useState(0); const [userCount,setUserCount]=useState(0)
 const load=async()=>{setLoading(true);try{const pqs=new URLSearchParams({q,status:paymentStatus,page:String(paymentPage)});const uqs=new URLSearchParams({q,role,page:String(userPage)});const [s,p,u]=await Promise.all([api('/platform-admin/overview/'),api(`/platform-admin/payments/?${pqs}`),api(`/platform-admin/users/?${uqs}`)]);setStats(s);setPayments(p.results||p);setUsers(u.results||u);setPaymentCount(p.count??(p.results||p).length);setUserCount(u.count??(u.results||u).length);setError('')}catch(e){setError(e.message)}finally{setLoading(false)}}
 useEffect(()=>{const id=setTimeout(load,250);return()=>clearTimeout(id)},[q,paymentStatus,role,paymentPage,userPage])
 useEffect(()=>{setPaymentPage(1);setUserPage(1)},[q,paymentStatus,role])
 const approve=async id=>{try{await api(`/platform-admin/payments/${id}/approve/`,{method:'POST',body:'{}'});toast('Payment approved and access granted.');load()}catch(e){toast(e.message,'error')}}
 const toggleUser=async u=>{try{await api(`/platform-admin/users/${u.id}/status/`,{method:'POST',body:JSON.stringify({is_active:!u.is_active})});toast(u.is_active?'User disabled.':'User reactivated.','info');load()}catch(e){toast(e.message,'error')}}
 const maxEngagement=useMemo(()=>Math.max(1,...(stats?.course_engagement||[]).map(x=>x.learners)),[stats])
 if(!stats&&loading)return <PageSkeleton/>
 return <div><Breadcrumbs items={[{label:'Home',to:'/dashboard'},{label:'Admin'}]}/><div className="page-heading"><div><span className="page-kicker">ADMIN CONSOLE</span><h1>Platform overview</h1><p>Focus on the few actions that need attention: learners, payments and course engagement.</p></div><div className="builder-actions"><button className="button button--soft" onClick={load}><RefreshCw/>Refresh</button><a className="button button--primary" href={`${BACKEND_URL}/admin/`} target="_blank" rel="noreferrer">Content manager</a></div></div>{error&&<div className="error-banner">{error}</div>}<div className="admin-stats"><Stat icon={<Users/>} label="Registered users" value={stats?.users??'—'}/><Stat icon={<CreditCard/>} label="Paid users" value={stats?.paid_users??'—'}/><Stat icon={<BookOpenCheck/>} label="Completed lessons" value={stats?.completed_lessons??'—'}/><Stat icon={<BarChart3/>} label="Revenue" value={stats?`${Number(stats.revenue).toLocaleString()} ${stats.currency}`:'—'}/></div>
 <section className="panel admin-engagement"><div className="panel-title"><div><h3>Course engagement</h3><p className="subtle">Unique learners who have started each pathway</p></div></div>{(stats?.course_engagement||[]).map(x=><div className="engagement-row" key={x.title}><strong>{x.title}</strong><div><i style={{width:`${Math.max(5,x.learners/maxEngagement*100)}%`}}/></div><span>{x.learners} learners</span></div>)}</section>
 <div className="admin-toolbar"><div className="resource-search"><Search/><input value={q} onChange={e=>setQ(e.target.value)} placeholder="Search users or payments" aria-label="Search admin data"/></div><select value={paymentStatus} onChange={e=>setPaymentStatus(e.target.value)} aria-label="Filter payment status"><option value="">All payment statuses</option><option value="submitted">Submitted</option><option value="pending">Pending</option><option value="paid">Paid</option><option value="failed">Failed</option></select><select value={role} onChange={e=>setRole(e.target.value)} aria-label="Filter user role"><option value="">All user roles</option><option value="learner">Learners</option><option value="editor">Editors</option><option value="admin">Administrators</option></select></div>
 <section className="panel"><div className="panel-title"><div><h3>Payments</h3><p className="subtle">Verify submitted references and grant access.</p></div></div><div className="admin-table"><div className="table-row head"><span>Item</span><span>Reference</span><span>Amount</span><span>Status</span><span>Action</span></div>{payments.length?payments.map(p=><div className="table-row" key={p.id}><strong>{p.item_title}</strong><span>{p.provider_reference||'—'}</span><span>{Number(p.amount).toLocaleString()} {p.currency}</span><span><i className={`status status--${p.status}`}>{p.status}</i></span><span>{p.status==='submitted'?<button className="table-action" onClick={()=>approve(p.id)}><CheckCircle2/>Approve</button>:p.status==='paid'?'Complete':'Waiting'}</span></div>):<div className="admin-empty">No payments match the current filters.</div>}</div><Pager page={paymentPage} count={paymentCount} onChange={setPaymentPage}/></section>
 <section className="panel"><div className="panel-title"><div><h3>Learners & staff</h3><p className="subtle">Search and manage account status. Use Django Admin for advanced editing.</p></div></div><div className="admin-table"><div className="table-row head"><span>Name</span><span>Email</span><span>Role</span><span>Joined</span><span>Action</span></div>{users.length?users.map(u=><div className="table-row" key={u.id}><strong>{u.name}</strong><span>{u.email}</span><span>{u.role}</span><span>{new Date(u.date_joined).toLocaleDateString()}</span><span><button className="table-action" onClick={()=>toggleUser(u)}>{u.is_active?<><UserX/>Disable</>:<><UserCheck/>Enable</>}</button></span></div>):<div className="admin-empty">No users match the current filters.</div>}</div><Pager page={userPage} count={userCount} onChange={setUserPage}/></section></div>
}
function Stat({icon,label,value}){return <div className="admin-stat"><span>{icon}</span><div><small>{label}</small><strong>{value}</strong></div></div>}
function Pager({page,count,onChange}){const pages=Math.max(1,Math.ceil(count/20));if(pages<=1)return null;return <div className="pager"><button disabled={page<=1} onClick={()=>onChange(page-1)}><ChevronLeft/>Previous</button><span>Page {page} of {pages}</span><button disabled={page>=pages} onClick={()=>onChange(page+1)}>Next<ChevronRight/></button></div>}
