import { useEffect, useState } from 'react'
import { CheckCircle2, CreditCard, KeyRound, Save, UserRound, BellRing, ShieldCheck } from 'lucide-react'
import { api } from '../lib/api'
import { useAuth } from '../context/AuthContext'
import { useToast } from '../context/ToastContext'
import PasswordField from '../components/PasswordField'
import Breadcrumbs from '../components/Breadcrumbs'
import { PageSkeleton } from '../components/Skeleton'

export default function ProfilePage(){
 const {user,refreshUser}=useAuth(); const {toast}=useToast(); const [form,setForm]=useState(user||{}); const [payments,setPayments]=useState(null); const [entitlements,setEntitlements]=useState(null); const [pw,setPw]=useState({old_password:'',new_password:''}); const [busy,setBusy]=useState(false)
 useEffect(()=>{setForm(user||{})},[user])
 useEffect(()=>{Promise.all([api('/payments/'),api('/entitlements/')]).then(([p,e])=>{setPayments(p.results||p);setEntitlements(e)}).catch(e=>toast(e.message,'error'))},[])
 const save=async()=>{setBusy(true);try{await api('/auth/me/',{method:'PATCH',body:JSON.stringify({first_name:form.first_name,last_name:form.last_name,headline:form.headline,organization:form.organization,avatar_url:form.avatar_url,learning_goal:form.learning_goal,learner_level:form.learner_level,notification_preferences:form.notification_preferences||{}})});await refreshUser();toast('Profile saved.')}catch(e){toast(e.message,'error')}finally{setBusy(false)}}
 const changePassword=async()=>{try{const r=await api('/auth/change-password/',{method:'POST',body:JSON.stringify(pw)});toast(r.detail);setPw({old_password:'',new_password:''})}catch(e){toast(e.message,'error')}}
 const resend=async()=>{try{const r=await api('/auth/verify-email/resend/',{method:'POST',body:'{}'});toast(r.detail,'info')}catch(e){toast(e.message,'error')}}
 if(payments===null||entitlements===null)return <PageSkeleton/>
 return <div><Breadcrumbs items={[{label:'Home',to:'/dashboard'},{label:'Profile'}]}/><div className="page-heading"><div><span className="page-kicker">ACCOUNT</span><h1>Profile & preferences</h1><p>Keep your account details simple and your learning recommendations useful.</p></div></div>
 <div className="profile-grid"><section className="panel profile-card"><div className="panel-title"><div><h3><UserRound/>Profile</h3><p className="subtle">Used inside your learning space</p></div></div><div className="profile-avatar-preview">{form.avatar_url?<img src={form.avatar_url} alt="Profile"/>:<div><UserRound/></div>}<div className="avatar-help"><strong>Your profile image</strong><span>Google profile photos appear automatically. Otherwise we use your initials.</span></div></div><div className="form-grid"><label>First name<input value={form.first_name||''} onChange={e=>setForm({...form,first_name:e.target.value})}/></label><label>Last name<input value={form.last_name||''} onChange={e=>setForm({...form,last_name:e.target.value})}/></label></div><label>Email<div className="verified-email-row"><input disabled value={user.email||''}/><span className={user.email_verified?'verified':'unverified'}>{user.email_verified?'Verified':'Not verified'}</span></div></label>{!user.email_verified&&<button className="text-button" onClick={resend}>Resend verification email</button>}<label>Headline<input value={form.headline||''} onChange={e=>setForm({...form,headline:e.target.value})} placeholder="e.g. Postgraduate researcher"/></label><label>Organization<input value={form.organization||''} onChange={e=>setForm({...form,organization:e.target.value})}/></label><div className="form-grid"><label>Learning focus<select value={form.learning_goal||''} onChange={e=>setForm({...form,learning_goal:e.target.value})}><option value="">Choose one</option><option value="research">Research skills</option><option value="communication">Business communication</option><option value="both">Both pathways</option></select></label><label>Learner type<select value={form.learner_level||''} onChange={e=>setForm({...form,learner_level:e.target.value})}><option value="">Choose one</option><option>Undergraduate student</option><option>Postgraduate student</option><option>Researcher / educator</option><option>Working professional</option></select></label></div><button className="button button--primary" onClick={save} disabled={busy}><Save/> {busy?'Saving…':'Save profile'}</button></section>
 <section className="panel profile-card"><div className="panel-title"><div><h3><ShieldCheck/>Security & notifications</h3><p className="subtle">Control account security and useful updates</p></div></div><PasswordField label="Current password" value={pw.old_password} onChange={e=>setPw({...pw,old_password:e.target.value})}/><PasswordField label="New password" showStrength value={pw.new_password} onChange={e=>setPw({...pw,new_password:e.target.value})}/><button className="button button--soft" disabled={!pw.new_password} onClick={changePassword}><KeyRound/>Update password</button><hr/><div className="preference-row"><BellRing/><div><strong>Learning reminders</strong><span>Show lesson and progress updates inside the platform. Payment confirmations still appear for your records.</span></div><input type="checkbox" checked={form.notification_preferences?.in_app!==false} onChange={e=>setForm({...form,notification_preferences:{...(form.notification_preferences||{}),in_app:e.target.checked}})}/></div><button className="button button--soft" onClick={save} disabled={busy}><Save/>Save preferences</button></section></div>
 <section className="panel"><div className="panel-title"><div><h3><CheckCircle2/>My access</h3><p className="subtle">Premium resources and courses unlocked for this account</p></div></div>{entitlements.length?entitlements.map(e=><div className="activity-row" key={e.id}><div><strong>{e.resource||e.course}</strong><span>Source: {e.source}</span></div><b>Active</b></div>):<div className="empty-state-action"><CheckCircle2/><strong>No premium resources yet.</strong><span>Use free lessons first, then unlock only what you need.</span><a href="/resources">Browse resources</a></div>}</section>
 <section className="panel"><div className="panel-title"><div><h3><CreditCard/>Payment history</h3></div></div>{payments.length?payments.map(p=><div className="activity-row" key={p.id}><div><strong>{p.item_title}</strong><span>{new Date(p.created_at).toLocaleDateString()} · {p.provider_reference||'Reference pending'}</span></div><b>{Number(p.amount).toLocaleString()} {p.currency} · {p.status}</b></div>):<div className="empty-state-action"><CreditCard/><strong>No payments yet.</strong><span>Your confirmed purchases and pending payments will appear here.</span><a href="/resources">View premium resources</a></div>}</section></div>
}
